### ISSUE TITLE
bumblebeed.Slackbuild don't git clone

### ISSUE THREAD

**Issue by ellingtonsantos** [jgeboski/Bumblebee-SlackBuilds#1]
root@darkelf:~/Bumblebee-SlackBuilds/bumblebeed# ./bumblebeed.SlackBuild 
Cloning into bumblebeed-git...
fatal: https://github.com/Bumblebee-Project/bumblebeed.git/info/refs not found: did you run git update-server-info on the server?

The problem is in this line:

git clone https://github.com/Bumblebee-Project/$PRGNAM.git $PRGNAM-git

Where $PRGNAM=bumblebeed

**Comment by jgeboski** [comment]
This is a result of the  Bumblebee developers renaming the repos and moving things around for Bumblebee 3.0.  I have updated the bumblebee SlackBuild for 3.0, and it should work now.  It no longer pulls from git, and now uses the the stable tar-ball release.

**Comment by ellingtonsantos** [comment]
Thank you!
